version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/kp-website/build
hooks:
#  BeforeInstall:
#    - location: scripts/before_install.sh
#      runas: root
  AfterInstall:
  - location: scripts/after_install.sh
    runas: root
